server:
  port: 8093
spring:
  cloud:
    stream:
      bindings:
        input:
          group: queue.notes
        income:
          destination: testIncome
        profile:
          destination: testIncome
          group: customerProfile